// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngtlgmslzxfubnnrttqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ndGxnbXNsenhmdWJubnJ0dHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDkwNTgsImV4cCI6MjA3NDY4NTA1OH0.dFp5fANBOMsny56IIPD6fVT01uBNsd9Lwq2XKHQB6M0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});